version: "3"

services:   
  client:
    build:
      dockerfile: Dockerfile
      context: ../Frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - server


networks:
  server: